_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
attention_dim:
    value: 256
batch_size:
    value: 16
decoder_dim:
    value: 512
embed_size:
    value: 256
encoder_dim:
    value: 256
epochs:
    value: 100
hidden_dim:
    value: 256
learning_rate:
    value: 0.0001
model_name:
    value: run_10
model_type:
    value: attention
